version: 3.7

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: ausbills/test.py
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
